### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AndyScherzinger** [SiKni8/BloodType#1]
Hi @SiKni8 ,

can you name the license under which this app has been released?

Cheers,
Andy

**Comment by SiKni8** [comment]
May i know the reason why you are looking for the license?

**Comment by AndyScherzinger** [comment]
I thought about probably playing around with it a little especially material design implementation on this app since it is a public repo on Github thus I can see and fork it due to Githubs TOS.
Most public repos are in fact open source projects stating the license thus it is well defined what I am allowed to do with the codebase.
In this case I am not even sure if i would be allowed to do any kind of changed on a fork.

**Comment by SiKni8** [comment]
Sure but please leave the original copyright and give proper credits for original work and as long as it is free, I have no issue with you changing it to material. I wanted to but didnt get a chance yet.

**Comment by AndyScherzinger** [comment]
Thanks! Playing around with it is basically what I wanted to do.

**Comment by SiKni8** [comment]
Ok great. Let me know if you make something awesome :). Thanks.
